### PR TITLE
Prepopulate url and create short url

### PR DESCRIPTION
**Pull request by alex-chou**
Created a cucumber test to test that a bitly link is shown on the create_link page. Cucumber test generate_unique_link should be passing.

### CODE REVIEW

**Comment by rshah17** [comment]
so overall this code looks good. my once concern is that we actually remade the controller so we did classrooms_controller.rb instead of classroom_controller.rb, as plural is the typical naming convention. so when we merge, this is gonna create two different files. would it be better for you to put your controller stuff into ours? not sure what the best way to go about dealing with this is...

**Comment by alex-chou** [comment]
I already merged your stuff into this branch prior to making more changes, so I've already moved over stuff from classroom_controller to classroom_controller, so the merge should have no issue.

**Comment by rshah17** [comment]
hmm did you use my most recent one? because I don't see the changes that I most recently made to classrooms_controller in yours..

**Comment by alex-chou** [comment]
There may be some merge conflicts, but it'll just be from the new changes you made, and I can fix those accordingly.

**Comment by rshah17** [comment]
ok should i merge the request? this lgtm

**Comment by alex-chou** [comment]
We can talk about it more when we meet in discussion!

**Pull request closed without merging**
